namespace PathFinding.Domain.Constants
{
    public static class MapConstants
    {
        //cells count for canvas/map  MAX_CANVAS_ROWS x MAX_CANVAS_COLS
        public const int MAX_CANVAS_ROWS = 64;
        public const int MAX_CANVAS_COLS = 64;

        //Unit dimensions UNIT_WIDTH X UNIT_HEIGHT
        public const int UNIT_WIDTH = 15;
        public const int UNIT_HEIGHT = 15;

        //let's define 2 colors for occupied and non-occupied cells.
        public const string OCCUPIED_CELL_COLOR = "7D945D";
        public const string EMPTY_CELL_COLOR = "EEEED5";
        //color for our moving unit.
        public const string MOVING_UNIT_COLOR = "D74840";

        public const string PATH_UNIT_COLOR = "9EAAD6";
        public const string START_POINT_COLOR = "FF0000";
        public const string END_POINT_COLOR = "00FF00";

        /* this is the input matrix. It is used for testing. This was done to ensure there is a valid path
         * A true value means it is a cell where our Unit can move to and false means the opposit.
         * */
        public static bool[,] MapMatrix = new bool[MAX_CANVAS_ROWS, MAX_CANVAS_COLS]
        {
                         {true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true },//(0,0), (0,1), (0,2), (0,3)....
             {false, true, true, true, true, true,false,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },//(1,0), (1,1), (1,2), (1,3)....
             {false, true, true, false, true,true,false,false, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, true, true, true, false, true,false,true, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false },
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {false, true, true, true, true, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, true, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, true, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, true, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, true, true, true, true, true,false,false, false, true,true,false,false, true, true, true,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
              {true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true },
             {false, true, false, true, true, true,false,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, true,true,false,false, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, true, true, true, false, true,false,true, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false },
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, false, true, true, true, true,false,true, false, true,true,false,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,true,false, false, true,true,false,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, true, true, false, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true },
             {false, true, false, true, true, true,false,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, false, true,true,false,false, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, true, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, true, true, true, false, true,false,true, false, true,true,false,false, true, true, true, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false },
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, true,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
              {true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true },
             {false, true, false, true, true, true,false,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, false, true,true,false,false, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, true, true, true, false, true,false,true, false, true,true,true,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false, false, true,true,false,false, true, true, false },
             {true, false, true, true, true, true,false,false, false, true,true,false,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {false, true, true, true, false, true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true },
             {true, false, true, true, true, true,false,false, false, true,true,true,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,true, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, true, true, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true, true, true, false, false, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,false, true, true, false,false, true, true, true, false, true,true,true , true, true, false, false, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,true,false, true, true, true,true, true, true, true, true, true,true,true , true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true},
             {true, false, true, true, true, true,false,false, false, true,true,false,true, true, true, true,true, true, true, true, true, true,true,true , true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true, true, true, true, true, true,true,true,true}

        };
}
}
